### ISSUE TITLE
`getVersionInfo': undefined method `edit_version' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by olamiwhat** [erikvillegas/itunes-connect-slack#18]
Fetching latest app status...
There was a problem fetching the status of the app!
get-app-status.rb:6:in `getVersionInfo': undefined method `edit_version' for nil:NilClass (NoMethodError)
        from get-app-status.rb:48:in `block in getAppVersionFrom'
        from get-app-status.rb:47:in `each'
        from get-app-status.rb:47:in `getAppVersionFrom'
        from get-app-status.rb:82:in `block in <main>'
        from get-app-status.rb:78:in `each'
        from get-app-status.rb:78:in `<main>'

Get this error after running the `node poll-itc.js`.  I'm not a ruby expert but it looks like whatever this block is supposed to be doing  in `get-app-status.rb`  is not doing it.
```ruby
def getVersionInfo(app)
  
editVersionInfo = app.edit_version
liveVersionInfo = app.live_version
```

**Comment by erikvillegas** [comment]
Hmm if I remember correctly the "edit version" is your app update in iTunes Connect that is pending deployment to the App Store. You might not have one configured. If you are still running into issues, you can also simply remove the references to edit_version to bypass the crash.

**Comment by olamiwhat** [comment]
@erikvillegas if there was no edit_version I would have expected it to return nil but it didn't. Anyway got it to work. looks like the `Spaceship::Tunes::Application` has been deprecated and updating that to `Spaceship::ConnectAPI::App` fixed it. `edit_version` becomes `get_edit_app_store_version` and live_version becomes `get_live_app_store_version`. Just some small refactoring got it to work for me. I could submit a PR for the changes that I made to make it work.
