### ISSUE TITLE
 get-app-status fails with require error

### ISSUE THREAD

**Issue by kenibarwick** [erikvillegas/itunes-connect-slack#7]
node poll-itc.js 
Fetching latest app status...
There was a problem fetching the status of the app!
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- spaceship (LoadError)
        from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from get-app-status.rb:1:in `<main>'

**Comment by kenibarwick** [comment]
Forgive me, school boy error... 

Install missing gem executables with `bundle install`

is needed first
